auth:
  type: LOGIN_FORM

spring:
  security:
    user:
      name: admin
      password: admin

kafka:
  clusters:
    - bootstrapServers: kafka1:19092,kafka2:29092,kafka3:39092
      name: kafka
      metrics:
        port: 9999
        type: PROMETHEUS
      
      schemaRegistry: http://schema-registry:8085

      kafkaConnect:
        - name: kafka-connect
          address: http://kafka-connect:8083

