global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'kafka_jmx'
    static_configs:
      - targets: ['kafka1:9997', 'kafka2:9998', 'kafka3:9999']  # 각 Kafka JMX 포트